import turtle
from playsound import playsound
#window
window = turtle.Screen()
window.title("\tNational Flag of Nepal")
playsound('national.mp3',False)
window.bgcolor('black')
window.setup(startx=300,starty=0)
#border for flag
border = turtle.Turtle()
border.penup()
border.setpos(-100,-100)
border.fillcolor('red')
border.begin_fill()
border.pendown()
border.hideturtle()
border.pensize(15)
border.pencolor('blue')
border.left(90)
border.forward(360)
border.right(130)
border.forward(300)
border.right(140)
border.forward(125)
border.right(215)
border.forward(290)
border.right(145)
border.forward(342)
border.end_fill()
border.left(90)
border.forward(110)

#moon
moon = turtle.Turtle()
moon.hideturtle()
moon.penup()
moon.color('white')
moon.setpos(-30,80)
moon.pendown()
moon.fillcolor('white')
moon.begin_fill()
moon.pendown()
moon.circle(30)
moon.end_fill()
moon.penup()
moon.pencolor('red')
moon.fillcolor('red')
moon.begin_fill()
moon.setpos(-30,95)
moon.pendown()
moon.circle(30)
moon.end_fill()
moon.pencolor('white')
moon.fillcolor('white')
moon.begin_fill()
moon.penup()
moon.setpos(-48,107)
moon.pendown()
for i in range(12): 
    moon.forward(10)
    moon.left(120)
    moon.forward(10)
    moon.right(150)
moon.end_fill()

#sun
sun = turtle.Turtle()
sun.penup()
sun.hideturtle()
sun.pensize(2)
sun.setpos(-45,-32)
sun.pendown()
sun.pencolor('white')
sun.fillcolor('white')
sun.begin_fill()

for i in range(12): 
    sun.forward(15)
    sun.left(120)
    sun.forward(15)
    sun.right(150)
sun.end_fill()

#text
text = turtle.Turtle()
text.hideturtle()
text.penup()
text.pencolor('green')
text.setpos(10,-180)
text.write('\tनेपाली हाँमी रहुँला कहाँ नेपालै नरहे \n \tनेपालै नरहे',align="center",font=("Verdana", 15, "italic"))
window.mainloop()